server:
  address: 0.0.0.0
  port: 8080

# ??????
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: MySQL
    url: jdbc:mysql://localhost:3306/expiration
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.pzy.pojo
  mapper-locations: classpath:/mybatis/*.xml

logging:
  file:
    name: log/log.log
  level:
    root: info
    com.pzy: debug

